### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by sidjain1903** [aalind0/NLP-Sentiment-Analysis-Twitter#1]
Hey,
After going through that code and pickled files, the "featuresets.pickle" file if missing.
Can you upload that too..

**Comment by aalind0** [comment]
@sidjain1903  Okay, i will upload.

**Comment by sidjain1903** [comment]
Hey, Can you please upload the missing file? It will be really helpful for my project.. Thanks

**Comment by aalind0** [comment]
@sidjain1903  Sorry, featuresets.pickle is a rather big file of size 312 MB. It can't be added here. You would have to generate it on your own pc.

**Comment by sidjain1903** [comment]
Can you tell me how can I do that. It will be really helpful

**Comment by aalind0** [comment]
@sidjain1903 Just make a pickle function for featuresets like i have done for other classifiers in Train_Classifiers.py and then run it. It will take approx 20mins till all the pickles are saved in the directory which you are working in.

**Comment by sidjain1903** [comment]
Alright..
Thanks alot
I hope it works
And if by any chance it doesn't, will that be any trouble for you if I ask
you again regarding this issue.

**Comment by aalind0** [comment]
No, no problem at all.  Will be my pleasure 👍
